"""update users and review table

Revision ID: 1afee0c643e2
Revises: 34e1c005bbcc
Create Date: 2019-07-08 20:34:36.198997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1afee0c643e2'
down_revision = '34e1c005bbcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodation', sa.Column('scores_accuracy', sa.Integer(), nullable=True))
    op.add_column('accommodation', sa.Column('scores_check_in', sa.Integer(), nullable=True))
    op.add_column('accommodation', sa.Column('scores_cleanliness', sa.Integer(), nullable=True))
    op.add_column('accommodation', sa.Column('scores_communication', sa.Integer(), nullable=True))
    op.add_column('accommodation', sa.Column('scores_location', sa.Integer(), nullable=True))
    op.add_column('accommodation', sa.Column('scores_value', sa.Integer(), nullable=True))
    op.add_column('review', sa.Column('is_anonymous', sa.Boolean(), nullable=True))
    op.add_column('review', sa.Column('reservation_id', sa.Integer(), nullable=False))
    op.add_column('review', sa.Column('scores_accuracy', sa.Integer(), nullable=False))
    op.add_column('review', sa.Column('scores_check_in', sa.Integer(), nullable=False))
    op.add_column('review', sa.Column('scores_cleanliness', sa.Integer(), nullable=False))
    op.add_column('review', sa.Column('scores_communication', sa.Integer(), nullable=False))
    op.add_column('review', sa.Column('scores_location', sa.Integer(), nullable=False))
    op.add_column('review', sa.Column('scores_value', sa.Integer(), nullable=False))
    # op.drop_constraint('review_accommodation_id_fkey', 'review', type_='foreignkey')
    op.drop_constraint(op.f('fk_review_accommodation_id_accommodation'), 'review', type_='foreignkey')
    op.create_foreign_key(op.f('fk_review_reservation_id_reservation'), 'review', 'reservation', ['reservation_id'], ['id'])
    op.drop_column('review', 'accommodation_id')
    op.add_column('users', sa.Column('gender', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.Text(), nullable=True))
    op.create_unique_constraint(op.f('uq_users_phone'), 'users', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_phone'), 'users', type_='unique')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'gender')
    op.add_column('review', sa.Column('accommodation_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_review_reservation_id_reservation'), 'review', type_='foreignkey')
    op.create_foreign_key(op.f('fk_review_accommodation_id_accommodation'), 'review', 'accommodation', ['accommodation_id'], ['id'])
    # op.create_foreign_key('review_accommodation_id_fkey', 'review', 'accommodation', ['accommodation_id'], ['id'])
    op.drop_column('review', 'scores_value')
    op.drop_column('review', 'scores_location')
    op.drop_column('review', 'scores_communication')
    op.drop_column('review', 'scores_cleanliness')
    op.drop_column('review', 'scores_check_in')
    op.drop_column('review', 'scores_accuracy')
    op.drop_column('review', 'reservation_id')
    op.drop_column('review', 'is_anonymous')
    op.drop_column('accommodation', 'scores_value')
    op.drop_column('accommodation', 'scores_location')
    op.drop_column('accommodation', 'scores_communication')
    op.drop_column('accommodation', 'scores_cleanliness')
    op.drop_column('accommodation', 'scores_check_in')
    op.drop_column('accommodation', 'scores_accuracy')
    # ### end Alembic commands ###
