"""add is_deleted column to accommodation

Revision ID: 68b66a87cad5
Revises: 1afee0c643e2
Create Date: 2019-07-17 20:39:00.181665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b66a87cad5'
down_revision = '1afee0c643e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accommodation', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='f'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accommodation', 'is_deleted')
    # ### end Alembic commands ###
